# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 13:10
from __future__ import unicode_literals

from django.db import migrations
import dynamicsites.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='folder_name',
            field=dynamicsites.fields.FolderNameField(blank=True, help_text="Folder name for this site's files.  The name may only consist of lowercase characters, numbers (0-9), and/or underscores", max_length=64),
        ),
        migrations.AddField(
            model_name='site',
            name='subdomains',
            field=dynamicsites.fields.SubdomainListField(blank=True, help_text='Comma separated list of subdomains this site supports.  Leave blank to support all subdomains'),
        ),
    ]
